### ISSUE TITLE
A* Pathfinding

### ISSUE THREAD

**Issue by kohoutekk** [KamilKohoutek/warcraft#29]
Pro správný pathfinding bude mapa muset být na mřížce, protože any-angle pathfinding je OP. Asi bude nejlepší mapu vytvořit v programu Tiled, exportujeme do XML a následně bude potřeba parser.

**Comment by charamza** [comment]
@KamilKohoutek Klidně, jestli to ten kód spíš nerozbije, což už se @Svaroslav povedlo, když mi kradl Cameru :D

**Comment by kohoutekk** [comment]
@herovis To přijde :)
